---
# tasks file for nginx
- name: libselinux-python & EPEL Rep install
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - libselinux-python
    - epel-release

- name: stop firewall
  service:
    name: firewalld 
    state: stopped

- name: disabled firewall
  command: systemctl disable firewalld  

- name: Nginx install
  yum:
    name: nginx
    state: present

- name: start nginx
  service: 
    name: nginx 
    state: started
    enabled: true 

- name: group add nginx
  group:
    name: "{{ nginx_group }}"
    system: true

- name: user add nginx
  user:
    name: "{{ nginx_user }}"
    home: /var/lib/nginx
    shell: /sbin/nologin
    group: "{{ nginx_group }}"
    append: true
    system: true

- name: nginx config template
  template:
    src: nginx.j2.conf
    dest: /etc/nginx/nginx.conf
    validate: nginx -t -c %s
  notify:
    - nginx reload
